name: pull request

on:
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: dotnet test . --configuration Release
      
      - name: Upload Test Results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: verify-test-results
          path: |
            **/*.received.*