name: pull request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ checkout
        uses: actions/checkout@v3

      - name: 🛠️ build
        uses: ./.github/workflows/build

      - name: 🧪 test
        uses: ./.github/workflows/test
      
      - name: 📁 upload verify results
        if: failure()
        uses: ./.github/workflows/verify-result